### ISSUE TITLE
Create a Distinct class

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Atoms#151] opened 2018-01-31 10:14 UTC
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
Works like LinQ Distinct methode

### Actual Behavior
Dose not exist

**Comment by Meerownymous** [comment] 2018-01-31 10:37
Duplicate of #150

**Closed by Meerownymous** 2018-01-31 10:37 UTC
Labels: Feature
