### ISSUE TITLE
Each has a ctor that exposes the current index

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#566] opened 2024-06-26 06:17 UTC
### Expected Behavior
Similar to `Mapped(Func<In, int, Out> fnc, IEnumerable<In> src)` the object `Each` has a ctor that has a signature like `Each(Action<In, int> proc, IEnumerable<In> src)`. The `int` in the `Action` is the current index when running through the enumerable.

### Actual Behavior
There is no way to access the current index.

### The log given by the failure.

**Comment by Meerownymous** [comment] 2024-06-26 21:06
This is a duplicate of https://github.com/icarus-consulting/Yaapii.Atoms/issues/493

**Closed** 2024-06-27 09:00 UTC
Labels: Feature
